# Data Cleaning

In [1]:
import pandas as pd
import numpy as np
import pyarrow

pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 100)

In [ ]:
path = "../data/us_flights_2024_all.parquet"
df = pd.read_parquet(path, engine= "pyarrow")
print("Rows, Cols", df.shape)
display(df.head(5))
df.info()
df[df["Origin" == "KSNA"]]

Rows, Cols (7079061, 110)

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,Tail_Number,Flight_Number_Reporting_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,Origin,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,Dest,DestCityName,DestState,DestStateFips,DestStateName,DestWac,CRSDepTime,DepTime,DepDelay,DepDelayMinutes,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrTime,ArrDelay,ArrDelayMinutes,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,Cancelled,CancellationCode,Diverted,CRSElapsedTime,ActualElapsedTime,AirTime,Flights,Distance,DistanceGroup,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,FirstDepTime,TotalAddGTime,LongestAddGTime,DivAirportLandings,DivReachedDest,DivActualElapsedTime,DivArrDelay,DivDistance,Div1Airport,Div1AirportID,Div1AirportSeqID,Div1WheelsOn,Div1TotalGTime,Div1LongestGTime,Div1WheelsOff,Div1TailNum,Div2Airport,Div2AirportID,Div2AirportSeqID,Div2WheelsOn,Div2TotalGTime,Div2LongestGTime,Div2WheelsOff,Div2TailNum,Div3Airport,Div3AirportID,Div3AirportSeqID,Div3WheelsOn,Div3TotalGTime,Div3LongestGTime,Div3WheelsOff,Div3TailNum,Div4Airport,Div4AirportID,Div4AirportSeqID,Div4WheelsOn,Div4TotalGTime,Div4LongestGTime,Div4WheelsOff,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum,Unnamed: 109
0,2024,1,1,8,1,2024-01-08,9E,20363,9E,N485PX,4801.0,12953,1295304,31703,LGA,"New York, NY",NY,36,New York,22,13871,1387102,33316,OMA,"Omaha, NE",NE,31,Nebraska,65,856,851.0,-5.0,0.0,0.0,-1.0,0800-0859,25.0,916.0,1120.0,4.0,1135,1124.0,-11.0,0.0,0.0,-1.0,1100-1159,0.0,NaN,0.0,219.0,213.0,184.0,1.0,1148.0,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024,1,1,9,2,2024-01-09,9E,20363,9E,N912XJ,4801.0,12953,1295304,31703,LGA,"New York, NY",NY,36,New York,22,13871,1387102,33316,OMA,"Omaha, NE",NE,31,Nebraska,65,856,851.0,-5.0,0.0,0.0,-1.0,0800-0859,16.0,907.0,1055.0,12.0,1135,1107.0,-28.0,0.0,0.0,-2.0,1100-1159,0.0,NaN,0.0,219.0,196.0,168.0,1.0,1148.0,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024,1,1,10,3,2024-01-10,9E,20363,9E,N918XJ,4801.0,12953,1295304,31703,LGA,"New York, NY",NY,36,New York,22,13871,1387102,33316,OMA,"Omaha, NE",NE,31,Nebraska,65,856,850.0,-6.0,0.0,0.0,-1.0,0800-0859,17.0,907.0,1104.0,6.0,1135,1110.0,-25.0,0.0,0.0,-2.0,1100-1159,0.0,NaN,0.0,219.0,200.0,177.0,1.0,1148.0,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024,1,1,11,4,2024-01-11,9E,20363,9E,N490PX,4801.0,12953,1295304,31703,LGA,"New York, NY",NY,36,New York,22,13871,1387102,33316,OMA,"Omaha, NE",NE,31,Nebraska,65,856,919.0,23.0,23.0,1.0,1.0,0800-0859,27.0,946.0,1154.0,8.0,1135,1202.0,27.0,27.0,1.0,1.0,1100-1159,0.0,NaN,0.0,219.0,223.0,188.0,1.0,1148.0,5,0.0,0.0,4.0,0.0,23.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024,1,1,12,5,2024-01-12,9E,20363,9E,N915XJ,4801.0,12953,1295304,31703,LGA,"New York, NY",NY,36,New York,22,13871,1387102,33316,OMA,"Omaha, NE",NE,31,Nebraska,65,856,851.0,-5.0,0.0,0.0,-1.0,0800-0859,24.0,915.0,1120.0,17.0,1135,1137.0,2.0,2.0,0.0,0.0,1100-1159,0.0,NaN,0.0,219.0,226.0,185.0,1.0,1148.0,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<class 'pandas.DataFrame'>
RangeIndex: 7079061 entries, 0 to 7079060
Columns: 110 entries, Year to Unnamed: 109
dtypes: float64(70), int64(19), str(21)
memory usage: 6.4 GB

KeyError: False

### Filter Data by Origin and Destination ###
##### Airport-> John Wayne Airport ######

In [25]:
df = df[df["Origin"] == "SNA"]
df = df[df["Dest"] == "SNA"]
display(df.head(5))

Empty DataFrame
Columns: [Year, Quarter, Month, DayofMonth, DayOfWeek, FlightDate, Reporting_Airline, DOT_ID_Reporting_Airline, IATA_CODE_Reporting_Airline, Tail_Number, Flight_Number_Reporting_Airline, OriginAirportID, OriginAirportSeqID, OriginCityMarketID, Origin, OriginCityName, OriginState, OriginStateFips, OriginStateName, OriginWac, DestAirportID, DestAirportSeqID, DestCityMarketID, Dest, DestCityName, DestState, DestStateFips, DestStateName, DestWac, CRSDepTime, DepTime, DepDelay, DepDelayMinutes, DepDel15, DepartureDelayGroups, DepTimeBlk, TaxiOut, WheelsOff, WheelsOn, TaxiIn, CRSArrTime, ArrTime, ArrDelay, ArrDelayMinutes, ArrDel15, ArrivalDelayGroups, ArrTimeBlk, Cancelled, CancellationCode, Diverted, CRSElapsedTime, ActualElapsedTime, AirTime, Flights, Distance, DistanceGroup, CarrierDelay, WeatherDelay, NASDelay, SecurityDelay, LateAircraftDelay, FirstDepTime, TotalAddGTime, LongestAddGTime, DivAirportLandings, DivReachedDest, DivActualElapsedTime, DivArrDelay, DivDistance, Div1Airport, Div1AirportID, Div1AirportSeqID, Div1WheelsOn, Div1TotalGTime, Div1LongestGTime, Div1WheelsOff, Div1TailNum, Div2Airport, Div2AirportID, Div2AirportSeqID, Div2WheelsOn, Div2TotalGTime, Div2LongestGTime, Div2WheelsOff, Div2TailNum, Div3Airport, Div3AirportID, Div3AirportSeqID, Div3WheelsOn, Div3TotalGTime, Div3LongestGTime, Div3WheelsOff, Div3TailNum, Div4Airport, Div4AirportID, Div4AirportSeqID, Div4WheelsOn, Div4TotalGTime, Div4LongestGTime, Div4WheelsOff, ...]
Index: []